<a href="https://colab.research.google.com/github/sunnyinAI/Med-spear/blob/main/ML_Assgn1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



---


1. Write a function to generate a data matrix X. Inputs: Number of samples, feature dimension. Output: Data matrix X. [1]

---


In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

def generate_data_matrix(num_samples, feature_dim):
    X = np.random.randn(num_samples, feature_dim)
    return X


In [3]:
X = generate_data_matrix(200, 5)
print(X)


[[ 2.56327253e+00 -1.67452233e-01  3.48029645e-01  2.01068087e-01
   2.88209929e-01]
 [ 1.37263528e-01  9.49306498e-01  2.91563916e-01 -8.87384430e-01
   1.61521561e+00]
 [-1.79409071e+00  6.96745930e-01  4.47139967e-01  1.35691125e+00
   1.78283656e-01]
 [-9.74666091e-01  1.41696014e+00  2.82356480e-01 -3.86086080e-01
  -5.26142237e-01]
 [-1.13241391e+00  1.48744363e+00  5.99395162e-01 -9.78199446e-02
   8.54601595e-01]
 [-1.84625674e-01  2.66404297e-01  5.49302056e-01  8.73013095e-02
   5.60565618e-01]
 [-1.66975135e+00  6.06628577e-01 -1.11508576e+00  8.10143770e-02
   6.79875353e-01]
 [ 1.10543122e+00  8.36851249e-01  9.70497491e-01  3.37906183e-01
   6.49855232e-01]
 [ 6.43027980e-01  2.65733510e-01  2.88016746e-01  1.22737099e+00
  -4.24132975e-01]
 [ 3.75988376e-01  1.38007849e+00 -3.50365144e-01  1.56936929e+00
   2.71873260e-01]
 [-3.62135165e-01 -2.44418757e+00  1.51257974e+00  1.25985192e-01
  -6.72852413e-01]
 [-1.31793686e+00  6.36364366e-01  7.49080592e-01 -3.85142425e-01



---


2. Write a function to generated dependent variable column t. [1]

a) Inputs: Data matrix X, weight vector for each column, bias w0, noise variance

b) Output: Target vector t


---



In [4]:
def generate_target_vector(X, weights, bias, noise_var):
    # calculate dot product of X and weight
    dot_product = np.dot(X, weights)
    # add bias
    dot_product += bias
    # add noise
    noise = np.random.normal(0, noise_var, dot_product.shape)
    t = dot_product + noise
    return t


In [6]:
X = generate_data_matrix(200, 5)
weights = np.random.randn(5)
bias = 2
noise_var = 0.1
t = generate_target_vector(X, weights, bias, noise_var)
print(t)


[ 1.97199731  5.30605948  1.58844456  0.77850175  2.13782717  2.98890898
  4.71760959  1.65316422  3.60547688  1.97747785  0.75485673  5.76294701
 -0.90142958  2.72526596  2.18516425  1.74421204  1.49094482  2.19967233
  2.1468606   2.55162157  4.5350857   1.55401321  2.27176292  2.16133185
  0.19027337  1.01852495  1.90441038  3.34334381  1.82631529  1.3796493
  2.5555245  -1.55348049  1.56458977  1.01481793  0.40446244  5.34268031
  2.02138881  0.9739972   1.63627982  5.0524463   1.93469785  2.82307352
 -0.22073767 -0.37010692  0.22989562  0.94616902  1.13944652  2.23018002
  0.71682105  3.20088262  1.53387961 -2.64251982  1.74122273  0.64245292
  4.11227377  0.10609973  2.70719459  1.30119735  2.86579388  1.88002417
  0.22204616  0.64794399  0.597158    1.22218199  0.77990376  2.64748051
  2.59241842  3.78110268 -1.44316299 -0.4805743   0.78216521  5.53072397
  3.16218851  0.19132215 -0.13770014  2.31527705  2.45201198 -0.29530476
  2.56964893  2.29297205  2.55247775  2.17924591  4.



---


3. Write a function to compute a linear regression estimate. [1]

a) Input: data matrix X and weight vector w

b) Output: y


---



In [8]:
def linear_regression_estimate(X, w):
    # calculate dot product of X and w
    y = np.dot(X, w)
    return y


In [9]:
X = generate_data_matrix(200, 5)
weights = np.random.randn(5)
y = linear_regression_estimate(X, weights)
print(y)


[-1.64617386e+00 -1.78300758e+00  3.53046692e+00 -2.53215951e+00
  8.72513124e-01 -9.78413479e-01 -2.47659552e+00  2.78534307e+00
  1.25136084e+00 -9.36733130e-01 -1.16801683e+00  9.29203365e-01
 -1.44655407e+00  3.09614732e+00 -1.50529997e-01 -5.37557791e-01
  3.03159135e+00  2.42760838e+00  1.86281708e+00 -1.55247423e+00
  3.06537006e-01  1.46926682e+00 -1.13306531e+00 -4.56359892e-01
  2.58779663e+00 -1.83583663e+00 -5.18631681e-01  4.22955076e+00
 -5.27546154e-01  1.67895008e+00 -3.79604115e-01 -7.21819175e-01
 -3.58562894e+00 -4.69343759e-01  4.45130550e-01  1.65590989e+00
 -3.02538336e-01  2.24704724e+00 -2.58480323e-01  1.77219789e+00
  2.19870959e-01  5.05965879e-01 -1.00544099e+00 -2.57317310e-01
  1.35556334e+00  1.60904093e+00 -1.99653385e+00 -2.80312240e+00
  9.63380644e-01  7.22292579e-01  1.86925545e+00  9.39393823e-01
  1.55983906e+00  2.78737122e-01  1.64134994e+00 -2.47022445e+00
 -1.81051759e+00 -7.40981233e-01  1.51040275e+00  6.84187373e-01
  2.36018582e-01  1.58955

4. Write a function to compute the mean square error of two vectors y and t. [1]

In [10]:
def mean_square_error(y, t):
    # calculate the difference between y and t
    diff = y - t
    # calculate the mean square error
    mse = np.mean(diff**2)
    return mse


In [11]:
y = linear_regression_estimate(X, weights)
t = generate_target_vector(X, weights, bias, noise_var)
mse = mean_square_error(y, t)
print(mse)


4.011687400461139




---


5. Write a function to estimate the weights of linear regression using pseudo-inverse, assuming L2 regularization [2]:

a) Input: X, t, and lambda

b) Output: w, MSE, y


---



In [12]:
def linear_regression_pseudoinverse(X, t, reg_lambda):
    # calculate the pseudoinverse of X
    X_pinv = np.linalg.pinv(X)
    # calculate the regularization term
    reg_term = reg_lambda * np.eye(X.shape[1])
    # calculate the weights
    w = np.dot(X_pinv, t)
    # calculate the estimate of the dependent variable
    y = np.dot(X, w)
    # calculate the mean square error
    mse = mean_square_error(y, t)
    return w, mse, y


lambda*phi+phi-transpsoe*phi)inverse.... Using numpy library... for matrix inverse.


In [14]:
X = generate_data_matrix(200, 5)
weights = np.random.randn(5)
bias = 2
noise_var = 0.1
t = generate_target_vector(X, weights, bias, noise_var)
w, mse, y = linear_regression_pseudoinverse(X, t, 0.1)
print(w)
print(mse)
print(y)


[ 0.52386843  0.01266608 -1.58158901  0.89080103 -1.21319585]
3.9618667181983342
[-3.07375407 -2.89848938  1.35192965 -0.13681812 -1.02185181  1.57954083
 -0.10905566  0.08054265  0.13111965  2.30419102  1.43662544  1.89415617
  2.42707472 -0.86311049  0.32103288 -2.98296039 -0.97814877 -3.57273898
  1.56967643  4.12966403 -0.55056542 -0.5604368  -2.16804703 -4.09211327
 -0.44144496 -0.97334259  1.59676234 -1.90330663 -1.70967012  0.44066891
 -2.51818688 -3.58937158 -1.86185585  0.26863257  1.0552888   2.86722508
 -2.61606433 -3.77808012  1.99867066  2.35032652 -0.5052027  -0.43661796
  2.06219574 -4.72281583  4.59205211  0.35870254 -0.39230521  0.95574714
 -1.25470343  1.14101993 -2.1651196  -2.74605922  0.43463852  1.90198515
  0.64335239  3.90349294  3.51338433 -0.19680066  1.27217374  0.77107511
 -1.50420108 -1.11410967 -0.34760442 -0.91775123  2.59450456  2.3670809
 -0.96948972 -0.83809998  1.74477897 -2.45854196 -0.06568954  1.67403948
  2.78583494 -0.48617845  0.61198531 -0.2782



---


6. Write a function to compute the gradient of MSE with respect to its weight vector. [2]

a) Input: X matrix, t vector, and w vector

b) Output: gradient vector


---



In [15]:
def gradient_MSE(X, t, w):
    # calculate the estimate of the dependent variable
    y = np.dot(X, w)
    # calculate the difference between y and t
    diff = y - t
    # calculate the gradient
    gradient = 2 * np.dot(X.T, diff) / X.shape[0]
    return gradient


In [17]:
X = generate_data_matrix(200, 5)
weights = np.random.randn(5)
bias = 2
noise_var = 0.1
t = generate_target_vector(X, weights, bias, noise_var)
gradient = gradient_MSE(X, t, weights)
print(gradient)


[-0.31249214  0.21852068  0.13459621 -0.61596106 -0.215278  ]




---


7. Write a function to compute L2 norm of a vector w passed as a numpy array. Exclude bias w0. [1]


---



In [18]:
def l2_norm(w):
    # exclude bias w0
    w = w[1:]
    # calculate the L2 norm
    l2 = np.sqrt(np.dot(w, w))
    return l2


In [19]:
weights = np.random.randn(5)
l2 = l2_norm(weights)
print(l2)


1.6313050292573257




---


8. Write a function to compute the gradient of L2 norm with respect to the weight vectors. [2]

a) Input: X matrix and w vector

b) Output: gradient vector, where gradient with respect to w0 is 0


---



for Q 5& 6 include bias term

for Q Note: bias think of average value of t and variance around its value. gradient can be set to 0 or exclude

taking 1/n for consistency


In [20]:
def gradient_L2(w):
    # exclude bias w0
    w = w[1:]
    # calculate the gradient
    gradient = w / np.linalg.norm(w)
    # insert a 0 in the beginning of the gradient vector to represent w0
    gradient = np.insert(gradient, 0, 0)
    return gradient


In [21]:
weights = np.random.randn(5)
gradient = gradient_L2(weights)
print(gradient)


[ 0.          0.12411992 -0.71635784  0.32237904  0.60621568]




---


9. Write a function to compute L1 norm of a vector w passed as a numpy array. Exclude bias w0. [1]


---



L1 norm now 
functions for single update of weights using GD
default value in functions 
calling the function we have to give x t may or may not lambda 12   
default value can be used except for x & t

In [22]:
def l1_norm(w):
    # exclude bias w0
    w = w[1:]
    # calculate the L1 norm
    l1 = np.sum(np.abs(w))
    return l1


In [23]:
weights = np.random.randn(5)
l1 = l1_norm(weights)
print(l1)


3.3479264733330094




---


10. Write a function to compute the gradient of L1 norm with respect to the weight vectors. [2]

a) Input: X matrix and w vector
b) Output: gradient vector, where gradient with respect to w0 is 0.


---



In [24]:
def gradient_L1(w):
    # exclude bias w0
    w = w[1:]
    # calculate the gradient
    gradient = np.sign(w)
    # insert a 0 in the beginning of the gradient vector to represent w0
    gradient = np.insert(gradient, 0, 0)
    return gradient

    
weights = np.random.randn(5)
gradient = gradient_L1(weights)
print(gradient)


[ 0.  1.  1. -1.  1.]




---


11. Write a function for a single update of weights of linear regression using gradient descent. [2]

a) Input: X, t, w, eta, lambda 2, lambda 1. Note that the weight of MSE will be 1

b) Output: updated weight and updated MSE


---



In [25]:
def update_weights(X, t, w, eta, reg_lambda_2, reg_lambda_1):
    # calculate the gradient of MSE
    gradient_mse = gradient_MSE(X, t, w)
    # calculate the gradient of L2 norm
    gradient_l2 = gradient_L2(w)
    # calculate the gradient of L1 norm
    gradient_l1 = gradient_L1(w)
    # calculate the total gradient
    gradient = gradient_mse + reg_lambda_2 * gradient_l2 + reg_lambda_1 * gradient_l1
    # update the weights
    w = w - eta * gradient
    # calculate the estimate of the dependent variable
    y = np.dot(X, w)
    # calculate the mean square error
    mse = mean_square_error(y, t)
    return w, mse


X = generate_data_matrix(10, 5)
weights = np.random.randn(5)
bias = 2
noise_var = 0.1
t = generate_target_vector(X, weights, bias, noise_var)
w, mse = update_weights(X, t, weights, 0.1, 0.01, 0.01)
print(w)
print(mse)


[-0.25546157 -1.73989483 -1.1365554  -1.09283896 -0.99420676]
2.9391732099723535




---


12. Write a function to estimate the weights of linear regression using gradient descent. [3]

a) Inputs: X, t, lambda2 (default 0), lambda1 (default 0), eta, max_iter, min_change_NRMSE

b) Output: Final w, final RMSE normalized with respect to variance of t.

c) Stopping criteria: Either max_iter has been reached, or the normalized RMSE does not change by more than min_change_NRMSE


---



Using 
loop function  called from 11
minm change 0.01 or 0.05 
maxm iterations may be 100 500 depends on eta
larger the eta lesser the iterations 


In [26]:
def linear_regression_gradient_descent(X, t, reg_lambda_2=0, reg_lambda_1=0, eta=0.1, max_iter=100, min_change_NRMSE=0.0001):
    # initialize the weight vector
    w = np.zeros(X.shape[1])
    # calculate the variance of t
    t_var = np.var(t)
    # initialize the normalized RMSE
    nrmse = float('inf')
    # loop until max_iter is reached or change in NRMSE is less than min_change_NRMSE
    for i in range(max_iter):
        # update the weights
        w, mse = update_weights(X, t, w, eta, reg_lambda_2, reg_lambda_1)
        # calculate the normalized RMSE
        new_nrmse = np.sqrt(mse) / t_var
        # check if the change in NRMSE is less than min_change_NRMSE


13. Run multiple experiments (with different random seeds) for, plot the results of (box plots), and comment on the trends and
potential reasons for the following relations:

a) Training and validation NRMSE obtained using pseudo inverse with number of training samples [2]

b) Training and validation NRMSE obtained using pseudo inverse with number of variables [2]

c) Training and validation NRMSE obtained using pseudo inverse with noise variance [2]

d) Training and validation NRMSE obtained using pseudo inverse with w0 [2]

e) Training and validation NRMSE obtained using pseudo inverse with lambda2 [2]

f) Time taken to solve pseudo inverse with number of samples and number of variables and its breaking points [2]

g) Training and validation NRMSE obtained using gradient descent with max_iter [2]

h) Training and validation NRMSE obtained using gradient descent with eta [2]

i) Time taken to solve gradient descent with number of samples and number of variables and its breaking points [2]

j) Time taken to solve gradient descent with number of variables and its breaking point [2]

k) Training and validation NRMSE and number of nearly zero weights obtained using gradient descent with lambda2 [2]

l) Training and validation NRMSE and number of nearly zero weights obtained using gradient descent with lambda1 [2]

m) Training and validation NRMSE for optimal lambda2 with noise variance [2]

n) Training and validation NRMSE for optimal lambda1 with noise variance [2]

o) Experiment (f) but, this time with number of training samples and number of variables [2

corresponding t and x as well
note the observation for 
500  100 70
generate multiple validation set or 1:10 training and test sets
code also to share for this using matplotlib or boxplot

optimal lambda ... corresponds to lowest validation error.... 
box plot for each one
first unit tested then generate result box


modularize the code 
observation >> variables naming >> explanation >> observation related to class >> 

SyntaxError: ignored